# Site settings
title: Raman Maan
description: A portfolio and blog for someone with kind of interesting, but mostly boring hobbies.
#baseurl: "/" # the subpath of your site, e.g. /blog
#url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Raman Maan
user_description: Computer Science Student. Software Developer. Level 3 Warlock in DnD. Coolest guy you don't know yet. Let's talk.
user_title: Computer Scientist

link_github: https://github.com/Raman-Maan
link_linkedin: https://www.linkedin.com/in/ramanmaan/
link_codepen: https://codepen.io/ramanmaan/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

site_color: '#54516A'

featured_projects:
- title: Neural Networks
  tags:
  - Machine Learning
  - Neural Networks
  - Synaptic.js
  - Javascript
  - Node
  desc: A collection of neural networks I've made as I learn more about them. My favourite neural network is an addition neural network I created in Synaptic.js that adds two integers together in their bit form. 
  link: 'https://github.com/Raman-Maan/neural_nets'
  img: '/assets/img/robots.jpg'
  img_alt: 'cardboard robots'
- title: Manning Construction
  tags:
  - Node
  - Sass
  - Javascript
  - Gulp
  - Bootstrap 4
  desc: I was hired to create a website for a local construction company, Manning Construction Company. This website is being developed as a Node application utilizing Bootstrap 4. Pug is being used for templating and Sass is used to handle styles. I'm using Gulp to expedite the development process and am hosting the website on an NGINX web server.
  link: 'https://github.com/Raman-Maan/manning-construction'
  img: '/assets/img/manningconstruction.png'
  img_alt: 'screenshot of manning construction home page'
- title: RamanMaan.io
  tags:
  - Jekyll
  - Liquid
  - Sass
  - Javascript
  desc: That's right! This website you're reading this on right now was made by me, utilizing a Jekyll template. Initially this website began as a hackathon project to learn about web technologies; since then this website has gone through many iterations. It started as a simple portfolio website, and how now expanded to include a blog! You can see some of the iterations in the README on Github if that's your type of thing.
  link: 'https://github.com/Raman-Maan/RamanMaan.io'
  img: '/assets/img/ramanmaan.png'
  img_alt: 'screenshot of RamanMaan.io home page'
