# Site settings
title: Raman Maan
description: A portfolio and blog for someone with kind of interesting, but mostly boring hobbies.
#baseurl: "/" # the subpath of your site, e.g. /blog
#url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Raman Maan
user_description: Software Developer. Level 3 Warlock in DnD. Coolest guy you don't know yet. Let's talk.
user_title: Software Developer

link_github: https://github.com/Raman-Maan
link_linkedin: https://www.linkedin.com/in/ramanmaan/
link_codepen: https://codepen.io/ramanmaan/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

featured_projects:
- title: Something
  tags:
  - Skill 1
  - Skill 2
  - Skill 3
  desc: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  link: '#'
  img: '/assets/img/mountains.jpg'
  img_alt: 'mountains'
- title: Something
  tags:
  - Skill 1
  - Skill 2
  - Skill 3
  desc: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  link: '#'
  img: '/assets/img/mountains.jpg'
  img_alt: 'mountains'
- title: Something
  tags:
  - Skill 1
  - Skill 2
  - Skill 3
  desc: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  link: '#'
  img: '/assets/img/mountains.jpg'
  img_alt: 'mountains'
